FROM public.ecr.aws/docker/library/archlinux:base

RUN pacman-key --init && \
    pacman -Syu --noconfirm && \
    printf "\n[community]\nInclude = /etc/pacman.d/mirrorlist\n" >> /etc/pacman.conf && \
    printf "\n[multilib]\nInclude = /etc/pacman.d/mirrorlist\n" >> /etc/pacman.conf && \
    printf "\n[archlinuxcn]\nServer = https://repo.archlinuxcn.org/\$arch\n" >> /etc/pacman.conf && \
    pacman -Syy && \
    pacman -S --noconfirm archlinuxcn-keyring && \
    rm -rf /var/cache/pacman/pkg

CMD ["sh"]
