FROM quay.io/sainnhe/gcc:latest

RUN apk add --no-cache \
    autoconf \
    automake \
    bash \
    bison \
    curl \
    file \
    flex \
    gettext \
    groff \
    libtool \
    m4 \
    make \
    patch \
    pkgconf \
    texinfo \
    xz

CMD ["bash"]
