FROM public.ecr.aws/docker/library/alpine:latest

RUN addgroup -g 1000 node \
    && adduser -u 1000 -G node -s /bin/sh -D node \
    && apk add --no-cache nodejs-current npm yarn chromium \
    && printf "CHROMIUM_FLAGS=\"--ozone-platform-hint=auto --no-sandbox --disable-setuid-sandbox\"\n" > /etc/chromium/chromium.conf

COPY docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-entrypoint.sh"]

CMD [ "node" ]
