FROM public.ecr.aws/docker/library/alpine:latest

RUN addgroup -S -g 1000 redis \
    && adduser -S -G redis -u 999 redis \
    && apk add --no-cache redis su-exec tzdata

RUN mkdir /data && chown redis:redis /data
VOLUME /data
WORKDIR /data

COPY docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 6379
CMD ["redis-server"]
